### PR TITLE
Add build.sbt and build instructions in README

### PR DESCRIPTION
**Pull request by samuelgruetter**
This is a cool project! However, when I wanted to run it, I didn't know how, because the README doesn't tell me how to build and run it. So I wrote a small `build.sbt`, and added instructions into the README on how to use it.

### CODE REVIEW

**Comment by marklemay** [comment]
I would prefer we leave the old pom. maven has better tooling integration then SBT.

**Comment by samuelgruetter** [comment]
Of course that's your choice, but I'm a bit surprised you think SBT (which is **the** build tool for Scala) integrates less well with tools than maven. What tools are you thinking of?

**Comment by marklemay** [comment]
The eclipse ide/ intellij ide last time I checked.  It probably makes sense to do the most idiomatic thing for Scala, so if that is sbt, we can do it.

**Comment by samuelgruetter** [comment]
Eclipse project files can be created by the sbt eclipse plugin: https://github.com/sbt/sbteclipse. And IntelliJ can import sbt files directly.

**Pull request merged**
